TEXT = 'SAEXJXFPLNSAPGRHGKCWELVRSPEZZXGUEVYNKGGWPKLDTKDTFZNRYTKLLLNTOMDZLYUHIBSIZTZVRSENYESSEOSIFPNPPRXZRRSEUORLULYVIWSQPDUOXHMHNWADXYDHRCLWHZIAOYKRSEVYTBRJSVDLRBTMZKOMYEEYEHMQSEQOSEBYTJKHIPPHRGOMLRFBXHEQSIAMESLLNQOMIELNGURIRLBNJQICWIAMLFMFTVZELYECEEDXYWLVYPHGYTBGOICAUAKLWGYEFYLWFPTHXYIBZFSUYXMEHRMPSPREGUHRNTKRGYHGCENRTWCOWUKCIFPWNYSIYOIAMHIFLVRGAVMMLRSTNSDTQUYXIYOJCSERDOEZZVFZWOORFSEWRTPIBEOSOYHMFTDATGIWYVHLGIPDBLQELOCHZELCERNIPMLNAFKTXRCITMPVCOAAGFXMXAGONEJPRGNPLYDAPIPWQEONRZXKZRRZPGFYOYURCRSAACPHMLNQONELEBRYFVCEHNZELCAHBTPXPLCRODYLOEGKNXYMLROLQQFRRZSERSIFKXTJZYRXDAGWLAUEFCSACVJXMQIAJXIMYHVYEEGWAAJTGCCTNOYPWOOAZHELETBYAILOTVSPMLLBNYPQCYTGXJMLRTBKITJLIASJWCWFGUELCXIPGWPCOOSLELCWAZVWMESTRXDFCQOEKELCJCBAWHPPAYODIUSOUKHEQHOEQTREQOEOEAYDOAKELGYGNYVMLRTUKXJMCASGGSSCWUKYMRSOHMSXRSIFCLWYCOHZTRCNOZSPVATAYIZRRCAPZMYRTTVYLRMEHRXPRRTRRRJXMORNMELCXIAZZXFPHBRPXFLTVYPIKEOUGGIBFGSUCQWDEYLTEJDOUGGIYYNNZZXFTNXUQMULSPUYJGOEAZTGMFLQLZPJZWGGWPKLDTKHMRSOHZOMQNOIKCCYYDUGOLMAEQNPAMFLQRPEBXEGUSIPMUGOOMBYTXTZARSEACSSGHOHROFCFPNMLMLDTJOELRSEEKDSSCCRYSIUTLYNLZCLVNOWEZWEVZHMJWBRNLVBEONBZMBOEGKNXGZNOEDXYJIAMLAYJLRZLPMYEOEQSJWOJOYKFTMGUELCZFSONIGALNTESFZLRAAMLLRYOYKRZNVZDLMFLQHPFSDYRTZYESTBMTZCXEPUGIPNAAEZYHZIASPLCCEJKYICOTBSLOCLNRCAPYYJBJTI'

def sortcount(count: dict):

    items: list = list(count.items())
    items.sort(key=lambda x: x[1])
    return [*map(lambda x: x[0], items)]

if __name__ == '__main__':
    count = {}
    print(len(TEXT))
    print(len(count))

    for i in range(0, len(TEXT), 2):
        bg = TEXT[i] + TEXT[i+1]
        res = count.get(bg)
        if res is None:

            count[bg] = 0

        count[bg] += 1
    
    print(sortcount(count))
