from math import ceil
import os


def generate_mapping(k, l, o):

    mapping = []
    
    for i in range(k):

        step = [2 * ((k - 1) - i), i * 2]
        acc = i
        stroke = 0
        while acc < l:
            if step[stroke] != 0:
                mapping += [acc]
            acc += step[stroke]
            stroke = (stroke + 1) % 2

    return mapping

def apply_mapping(text, mapping):

    new = ['\0'] * len(text)
    for idx, letter in enumerate(text):
        new[mapping[idx]] = letter

    return ''.join(new)

def railfence(intext, key, offset):

    mp = generate_mapping(key, len(intext), offset)
    out = apply_mapping(intext, mp)

    return out

  

CHALLENGE_4_A = '''IIAFW OSIHP FNRGO AAONP GLOOY VRNEE EAPNX NLTAA NIOOF ORIJD DESSI PAAPE NREAC TAETH DEFNO ETAHL CSSTA HENTE AIGWS NOTIG EOIBD PSOAP TIDNE TBKUI WNHET AADTN AHEED ODNDW TTEOH SRAET AUTRN TWNIH XOEEP ACITT SOWNI AASSL NOUUS RRSPI TEADH HTNWE HICCE DKNEI TWTIH CHNEO ECGIR WESIA LTTOD THHAT OEKBO GIANH EDNBE NCEAC ELBLD TUATH HTYTE NOLUG YAADH ESTLF UYMOA SEGSA IETSR EHVEN OEELP NCAOT EIAND OSTHR TNEOE RNPCY DTIEW ATHHS TIOFT OPERT ICFTT MRAOC ASPUL IRGYN NCAOT IIGNN RFHUT IESRN UTTRC NICOS NORRE DOVFA AIDSN IMEAN HITGT RHYIT VFYIE ROBUE IUGYN ETIHD RNAEW ESIDF TNLIE OYIJD SEYST TLEEH NLWOG LAFLO AGSLS TAETH OFTRN DAHNT IERMR OOERV HRBTE MAARE SNETH UCDOL TWHAC EEYVR ITGHN ATWHT GAISO ONIGN INESD DAUNO ITESD TAETH MSTAE EIHMS AETHD EAAKN BTEAL TIENH RCEON NRHAD HARDE CBTAK HOWTE DIWNO TBHUS AEMSW PERAP COAAH SNODT UOTDP EOTME IMFET TEILL NKTEO NHHIG CAADH ENTGD UHHOG EEYVR ITGHN DHNAA SDTIA WDOON OPIPS HTREE GERAE GTTOE LTIAK WNAGE BTREU RGAES FNIDR AEDSN RINDA OKFCF WEIEH JLDEO DIAER WNTKA YEURO PNOGE EPLLA ELMSE DTTOO THOAN DWNIO NTWKO WHHOT SEAYT WYKAA UECOR VORNE TSOAI ANGRN WEDDI YEVLO BENRA IKEVD YOTSS SEHMT AELVU CTEAC PSOSR CTLOO NSWAD THEAW DHAAE FCUHO ONTDU OATBU NLFYN NRAAK ANNDN MATSI EHVWE SEENP ANHTW EIALT ILGKN OATBU ETIHH OSYTR TOEFH SPIOT OTENT ETEHY OLTLW SAHGT FASTE OTEON RVSEY UEICR RTPYE TOHRT AEEYR EALRA GLOYO EDPTM AOYRR YWOAT RMNAK EOWTS HIUTO ETVLA GIPNA MENRA TERNT EAUCB UTLOR GOSNE OTITP ACCWS NHSIE HERCA TARCE NSNAD BURME SSEYT TMESH RCOUI DUSSE NIIGS HNDTE OEIPS OTLBX SIADH TDRAT TADCE BUTSO THAIW LSACE YRBLA AIYNR CEDNO GIFNO MSKOE DINNA ODIJD AEAHD ELDRA OYENT HDTTA ETAHM IRGKN ESEWR IUUNQ OEATE BCXHO AWIHT DHTAN ARIEL DSUEB HTUSO HLVDA OEEDN TIASH HTSTI CIUNL DDHET QEASU ORTEU NLTIE THPAA APEER NDOOS OMTEF DHSEE NIAGS NNTDO HORTE HSFTE TAHCT TAETH SDGEI DNDSI TNEOR APOET RVHET EEESV UNDHN DRDEO ODEBX NSHIT AELVU ETNMA HTTTA ITHHS TABDO HECTE EAHST EERRA NEYOL VFHIE DUENR NDTAD LWEEV MNEUB CRNSO SSIIT ONNGF EIINB RNDAY IISGT WSTOI UHTOT OHTEU NLTIE RHWEE LONUD HOVTA EENBE OEGNU EHIDS SGONF ARHEC XBOOT VHIAE OTNSW MNEUB FREAT WRHTO ROWUS AECHD CREAK HDDTE IENSG TBEUW NRCEO SLROE UTDON SEART INGDN AWIHT ETNMA ITEFV NHRUD AEDDN ETVWL FEHOT IETPC ROMGA ESEWR TOIUL DNNEI EABRD TOEXH MRIEA NNTIG HWNOU EDARD FNRDO ETGYI WHRTE OETNT OHTEU NLDIE CPOIT AGSRM NREAG RDMFO NNZIE OETRS IOENN EOWNS LHTIE SHWOE HIUTO HTOTE LUNTI AEGRN FEODR IMENN RZSEO STVOE OEENN NSTAD ZWROE IOWST NAMST HUOCT OGBON WUFTE UIEGR UDTOT THHAT UELOT EIHNS LOBUD NEEIT RRTPE AEADS DNIAD OTAIN ILIDG NTHIT CISSA ZERAE FOTII SWRAP EETSN DAONA INNEF TOATH ETTTN IHIDG ATEGV ORFOM OOERV TROAH AUDSN SDGEI PNESL YNOTF HRBTE NOMXU RBTES RHWEE SAIST TLELH SIESU HOWFO RTAOE HDBTE AIYNR GDTII HSDTE IENSG DJEOI DHEAS TNLTO NYANH EDESV LROAP ISLSB NEEIT RRTPE IANTO USTBT MHSEO TTASR HIFGT WORRA ADTWS SOUAS WMSEE UHDOL ARTED DHGEI SIETL TFRTO HIAGT TNPDO BTTOO MTIOG NVOIG ZNREE NOOOE ZNREE EOOZR RZOEO ONEEN IODRN IEACM HLETR UEDHN DRNEA IDTFF IYEFV RTEHE VFFIE EITVI OTUOK WSMTO UIENT NSHOT EETWB AOEMK ETOHC ENTNC NIEOB ETNWE ATAHT TNEDH LCEUP RPAEB BNTKU AIEHV EALFE GIHNT IAWTT LIALT UKAES TLOOL ENTGR IOUFG ORTEU ETIHS IGINF NCEAC WWUEO HLVDA OEKWR OEIDN OTLFR GORNE TBHUT IEONG CTLAA NLAAN ASHCR BAEDE ONNFU NDHIT AEELK HBNEI HDCTE NORUT LYBCU ETEHR SWOAN GSOIN EFBHR TUETH IYRDD OEECV ERPHR NHAOE WNTDI LHTAI ETELH FLOPR UMFOR ERDIN NSHIT EEHTC VDSII NIEOW NMGAA TERDO REETI TVEEH TACTA DHNEE YCTRP MESDE GSFAE MRTOI SIETE TMBSO REIAA ELCFN IEHCP AEDRN OIEHP AWEER TNOOT AOELT FTNOI NDAAN'''
CHALLENGE_4_B = '''LESIE DKRRO SICER RNDEE ACITE VSSEE EICEV SHSRT RGSEI HLEIV OIETE BANND EOIGO IAECD EASUT FAMDE YAUHF HIWMU SASEH TTTTA IMETM CEAGN NBTEG OEDRO ADLEP UUWPM FFLIE UTIYA IRBED KECTC IATOL LGTOP RIWMI THRDI EOCSF IRYDE ITFNE OHRFO EHITN NEMVS MRNUR SOHNR RISUD HMTDH BDGVC EHREE YBSEU TOTDH LEARI DTLRN TIAST DHNEA CRTHS DEAGU ERDTE TEHEI ELHFT SNEFR RCOND RSOEW DIWYF HOBNW GOMDA WIYHR ABPRB TTEGE TAENO EAPSR IPTLE CKDYO TOIYA HNHRF SDEEH PUTEO DORAS MEAOT EWDEL RWMEO NVHAE SEETS RFSOI LMMIA LBISI ILEAT AEOFE OEMMM QINHT MDOTB DEEIE AFWNT AEHSO UNHTI FAGBR HCULB UIIHI WGOEH TATKA MANIA CIUEO REAAE SXITD RRWES MHERH AOSSA EIRIL EPTEA WECII NEDHA AIHOE ASTOS RAEEA DOFHN EECSE EEIYE GENIO TSTGH UEDAA SBRLD SHIHE VIHEN NHETJ IAATG AEADD NIINT IANEW IEDLE ONRLG EHDOT NMESA AIESN EGTBG LDIRY ETODL GARNM MXALV HAEEO EYIRM TLBHK DNLEL EEHNE OHELI AOEAV TIERD EOHQT TOEYY THABH TCCDE TLLOI AGWSA IWLAO ONRIE NELUP SOTHW BCADA RMSST FSOEL PIMNO EEELI EFFRT NIEDE ESCHN DAKIN JARTH NENHN HNECN AYDFH IETRO EKOET HEHIE PPOEC EHSEH TATLA JDRET HMSOO SADFR SEPYE AHTOD EHFNC VSMGP SOOEI TLRSH DIEOL AETTS CNOWS GOTVN UESRH NNMNO IOFEN CTJSM HTIAE GRITL ETEEU EAEII NIHVT OLNIM FLADE TTATE MDRAE REEUI ATSER FWADT BRAEE AEAOW LHITG RUTCU NEULY ATNRU SNMWU EAFWA OSAEE STEOL TALEP EKNDY NLWIK SREIS MACUK EOJEL ILKNA SYOUE ASSDV UHRWO UHNHD TUEIM TELBT KRITD IEEGR CHDDT ANOEI EUNON VEKLO SEOTB RITML OKAMO RSIOO UPMNT TMFMD IONIN ENTIA TWHEH OASAK ASRGM TOARI AONTH TAPAN TNBED NETML RTFAS ORBHE OIEIY DUVRH UHTLI ADHEE EEOEN LLIYT RYEAE RTSSS AHLOD E'''
CHALLENGE_6_A = '''NNFYR LKWAN SARTO AOFLA XEERB OUATD EDIHS TPEAP RACEO NFARC OELHA GUEEL EMAHD SGOOA DETEM TPAOL OTOTO RRWIK BUTDS EASKE EHHEW TRDGQ UNEOI ONTWS REIES HEINH SSADO EFTSH ESAII GHRTL WASTN IUCHM BTITW TAUNO UEGSO RATIH OURES SPICS IUTHE NPOIC ELHOS ETDUA ARRBI PSANR DENTS EATNG TOHLE ACBHE KEEOP TGHTI SSRSA EWEBU TYTAT DIADH STOTP NDRIS VUGPA NSIHE ITNTS TIEGV IONTS AETHT EIADW OARTR ASIST ANHDG LLLEI WNDTA HTARS CEEED TMOEV EVAEH EDORF EHEHT IFWAY HAGEN TDEND THEER TERAV WAPEA BIEBA LNBHA TTWKL DHUAO SLOEW VITRD IETDO HWGHE DTRNE RSVHI LDHUA OHADE PVNTY EOLIM ETTFT OPSOO EAPLO RIFTT HUWER YEENS COICS WEUWO LFILN IUTTO ODRRO OWMTH EFRIA SAWNE HINTG YONGR WWHTH TEIAK ERSBT ITUSB MSTEO EUCHM OOCOI ANFDE NICCH ATTTE CAREM HSEDS TISAN EDHAV IENLS SEENG ALLIY TTRAO CNONI STKAY IWNST HEOWT ERITT ASODL IATFE NEDIK ELALC CIADN TTHNA ETHII TTEVE HRTEE PDEYS POTTS THENS ORELO IHENS EUNNG IITRU LDOBW IDDHE EROMF VNWTH EEIRW AASCA NDTIS ONTGH NEACB HEAIN RIDWI TGHNO ARHDA CRIFM OCENS EEVES NTIAT OGRIW ARSMS GARNO IDITN TUREW EAHOA MNBSA NCLEU RSIOG NFABO ONBUT YPDIC ELDOE RSVWI EPRRE ERINA GPSEA ORTWH EHNCL EFETW YBEAI MTOOM OAIMI TSPCB UITTO NTDTI NKTIH HWILY LENDA INFHI NTGYG UEYSM STHIA SNNAA HTBEE SNADN AIPKD ITEWP LDNUT OTHEE FBSTT RIITH AETMD HAAPH NEDET PBANA KOFIC FIOTH OLUAI TWHAG SUAUL SPRIY OLOTH TEREA KRIBI THWTN VICET HFORM CITOH DAEOV EDRNU LTACV ESIDN OCHAX NEFOR ETGIR FERHD OMEIE ULDON CUITQ ETEWH EYSME OONSO ULWDE KIDEN BPEDP AAERT THFRI MCEET IAUMB PINOG HATTH HTTTA ACEDM EESHG EMAIS TEXHP GINIA TLWAS TUIRT HOONX FOORD ICHHR WDILA LEALB GUEMA NIATD TOEGG THETL EPLIM GAERS TTHUT APTOC EOANR LLSAT CHEMT OOLEN IUBER SBOML LTAHF ENISO EANKB ORICI FAFTO GSELE RWHIT THEHP TPLEO IEYNN LFNNK SAORI CEFCF LTRLA ASDOE NCIVE GYTAS MUUOA SAHNC TERNC ITCAP NETSI UGBLS IANNL LIEGT CEHNA ELWAA YSEEN BASGP AIRBF BOOST ORKWA SJUSD TNOWI NNKHO IWSGL LIANC HOAWN GHENW TDYCA ELHDC AENLL LYEOT LOTAT USISI DHBLY UTOEI FUYRC ANUCO SSROE RRENE CFALL CSETH EOBTA VIHOE OFARS UPECS TUJOD OISET USPEI DEVOA AKETO SONBT OUTHE HBTKA NNDAE VBHAT AGAQI HREAB KNGAL NLIER UHLTA NDSWE ATASN EAITW EDORS FODTH IENMO HATPG NWEEQ PCKLI YUOTT PESPA TATDN LYRNE ADOHN NALLC EEHOR WARTH RGENI METSE OMARP FRENA TPRAN YDLLO CMAOO NSIAT EVEDR NIMET LYNIM NMYIA TDEEL EFYTL OEVHE WHEWS ARALK TISTO AGNNE ADHED ORAFQ DETSI PUTOT TAOTH EECKL ITLWA NTPSO AIBLS ESLIS OTTIN BNUEE DIWDT NAGAE MGETO TTGEO ELHAT ICOOA TADFN MTHOE RTWOE RNNDW AEKAB LEERC ROOST EFERR SCEIN TETHA ITWTT HXAEA DBHET SENNT ESTBU EJRET OHFHI RTDET HOFSO ALLCS EILEH WWOUL CDELI STTNT OTNHE ALLCS ETHOI UWWAR ARTTA TNEAI SNTOX UTOAM TICAT LAENC YRLTE DPBYH ESTYY EMSTO SELAH MTIGH LTPSW ERREB LEATE EADRI ONDCA OTDSE LEUAT THHTE NDSEE ADAHD RDALE ADROF EEYRY PCTNN THOEI ELFST MTGAA VHHET TEESU FMFAI ENCTI USEAT COGIL TOANO SFACI AILFT ERNCI TANPD ENDIA THERI VFODI EOSJL CUALC IONTS AERIR GAITU TSHAV ISGEE RENCE HERPW IHPET RIDFI OVIUT WBEEN THOAD TIMEE VCRAO CTTNO IWKWE HSAAA NOETV RLEEA HOFOT LDWIN ONLYO RWKEK NOEWW UCAON YITFO ODSAN UDROK FOOLA RDWTR EEISN OOURY DGRYP CTE'''

if __name__ == '__main__':  
    intext = ''.join(CHALLENGE_6_A.split(' '))

    for i in range(5, 10):
        dec = railfence(intext, i, 0) 
        print(dec)
        input()
        os.system('cls')
    
    